channels:
- defaults
- conda-forge
- pytorch
dependencies:
- python=3.8.2
- pytorch=1.6.0
- pytorch-lightning==0.9.0
- torchvision=0.7.0
- pip
- pip:
  - mlflow
  - cloudpickle==1.2.2
  - boto3
name: mlflow-env