channels:
- defaults
- conda-forge
- pytorch
dependencies:
- python=3.8.2
- pip
- pip:
  - mlflow
  - sklearn
  - cloudpickle==1.6.0
  - boto3
  - transformers
  - torchtext
  - prettytable
  - spacy
  - captum
  - ipython